vim.g.did_load_filetypes = 1
-- require 'setters'
-- require 'autocmd'
require 'mappings'
require 'snippets'
require("lists").setup()
require("git").setup()
-- require 'debugHelper'

-- require 'plugins.cmp'
-- require 'plugins.gitsigns'
-- require 'plugins.lspconfig'
-- require 'plugins.lspkind'
-- require 'plugins.lualine'
-- require 'plugins.bqf'
-- require 'plugins.treesitter'
-- require 'plugins.harpoon'
-- require 'plugins.telescope'
-- require 'plugins.dap'
-- require 'plugins.navigator'
-- require 'plugins.comment'
-- require 'plugins.lightspeed'
-- require 'plugins.luasnip'
-- require 'plugins.indent-blankline'
require 'plugins.todo-comments'
-- require 'plugins.sort'
-- require 'plugins.chad-tree'
-- require 'plugins.dial'
-- require 'plugins.dashboard'
-- require 'plugins.barbar'
-- require 'plugins.diffview'
-- require 'plugins.neovim-cmake'
require 'plugins.presence'
-- require 'plugins.project'

require 'setters'
