-- local luasnip = require 'luasnip'
--
-- luasnip.filetype_extend("javascript", {"javascriptreact"})
-- luasnip.filetype_extend("typescript", {"typescriptreact"})
-- luasnip.filetype_extend("javascript", {"html"})
-- luasnip.filetype_extend("typescript", {"html"})
